In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras

In [4]:
df = pd.read_csv('MorthDataSets/TR_Accident_Vehicle.csv')

In [5]:
df

,Unit_ID,Registration_Number,Crime_No,Vehicle_Owner_ID,UserID,Modified_Unit_ID,Action_Flag,Sync_Id,Sync_Id_Old,DEDT
0,57,AP26AY1382,2018000071,2018000397,4400061,0,N,-1,-1,7/25/2018 18:50
1,57,AP26AY1382,2018000071,2018000397,4400061,0,N,-1,-1,7/25/2018 18:50
2,57,AP28CK8490,2017000064,2017002647,4400014,0,N,-1,-1,9/25/2017 18:17
3,57,HR38Q9825,2014000243,2014001174,4000039,0,N,-1,-1,12/1/2014 12:28
4,57,KA-09-EU-5865,2014000111,2014000332,4100020,0,N,-1,-1,4/22/2014 21:01
5,57,KA-09-EU-5865,2014000111,2014000332,4100020,0,N,-1,-1,4/22/2014 21:01
6,57,KA-09-EU-5865,2014000111,2014000332,4100020,0,N,-1,-1,4/22/2014 21:01
7,57,KA-09-F-4363,2014000111,2014000330,4100020,0,N,-1,-1,4/22/2014 18:21
8,57,KA-09-F-4363,2014000111,2014000330,4100020,0,N,-1,-1,4/22/2014 18:21
9,57,KA-09-F-4363,2014000111,2014000330,4100020,0,N,-1,-1,4/22/2014 18:21
10,57,KA-09EY4016,2014000043,2014000140,3200150,0,N,-1,-1,2/22/2014 13:48
11,57,KA-10-150,2014000043,2014000138,3200150,0,N,-1,-1,2/22/2014 13:26
12,57,KA01C8153,2016000073,2016000372,5600028,0,N,-1,-1,9/7/2016 13:06
13,57,KA01C8153,2016000073,2016000372,5600028,0,N,-1,-1,9/7/2016 13:06
14,57,KA01C8153,2016000073,2016000372,5600028,0,N,-1,-1,9/7/2016 13:06
15,57,KA01EB0650,2014000176,2014000509,5300024,0,N,-1,-1,7/2/2014 19:44
16,57,KA01HA4212,2019000012,2019000099,4200023,0,N,-1,-1,2/26/2019 13:41
17,57,KA01HA4212,2019000012,2019000099,4200023,0,N,-1,-1,2/26/2019 13:41
18,57,KA01P5716,2018000004,2018000024,4400112,0,N,-1,-1,1/15/2018 11:26
19,57,KA01P5716,2018000004,2018000024,4400112,0,N,-1,-1,1/15/2018 11:26
20,57,KA01P9020,2018000054,2018000250,5700038,0,N,-1,-1,6/17/2018 18:07
21,57,KA02EF7354,2018000072,2018000417,89700010,0,N,-1,-1,8/12/2018 18:22
22,57,KA02EF7354,2018000072,2018000417,89700010,0,N,-1,-1,8/12/2018 18:22
23,57,KA02EF7354,2018000072,2018000417,89700010,0,N,-1,-1,8/12/2018 18:22
24,57,KA03HF652,2014000176,2014000511,5300024,0,N,-1,-1,7/2/2014 19:52
25,57,KA04MA4283,2014000244,2014001178,5300053,0,N,-1,-1,12/2/2014 11:46
26,57,KA04MA4283,2014000244,2014001178,5300053,0,N,-1,-1,12/2/2014 11:46
27,57,KA04MH5753,2016000059,2016000335,5600028,0,N,-1,-1,8/7/2016 21:08
28,57,KA05EN5476,2014000061,2014000296,5900092,0,N,-1,-1,4/20/2014 18:40
29,57,KA05M5108,2016000009,2016000112,5600028,0,N,-1,-1,3/7/2016 21:31
...,...,...,...,...,...,...,...,...,...,...
410335,1895,KA51C8444,2016000027,2016000128,189500002,0,N,-1,-1,4/9/2016 18:34
410336,1895,KA51C8444,2016000027,2016000128,189500002,0,N,-1,-1,4/9/2016 18:34
410337,1895,KA51C8444,2016000027,2016000128,189500002,0,N,-1,-1,4/9/2016 18:34
410338,1895,KA51D8932,2018000175,2018000861,176600065,0,N,-1,-1,11/26/2018 19:39
410339,1895,KA51EC1967,2015000062,2015000361,189500002,0,N,-1,-1,6/27/2015 11:13
410340,1895,KA51EF6863,2018000043,2018000303,189500022,0,N,-1,-1,4/20/2018 19:26
410341,1895,KA51MC5233,2014000004,2014000153,25900026,0,N,-1,-1,4/4/2014 19:37
410342,1895,KA51MC5233,2014000004,2014000153,25900026,0,N,-1,-1,4/4/2014 19:37
410343,1895,ka51y7115,2016000177,2017003089,189500022,0,N,-1,-1,5/18/2017 17:41
410344,1895,KA53-U7927,2014000054,2014000472,25900026,0,N,-1,-1,9/4/2014 15:45
410345,1895,KA537622,2015000105,2015000591,189500002,0,N,-1,-1,11/26/2015 20:44
410346,1895,KA53A3437,2016000427,2017000066,189500022,0,N,-1,-1,4/4/2017 20:01
410347,1895,KA53A9490,2017000053,2017000885,83100002,0,N,-1,-1,4/20/2017 12:47
410348,1895,KA53B0218,2015000194,2016000292,189500002,0,N,-1,-1,4/22/2016 19:36
410349,1895,KA53C1731,2017000410,2017004015,189500025,0,N,-1,-1,12/9/2017 2:25
410350,1895,KA53C1956,2017000142,2017000866,189500002,0,N,-1,-1,4/20/2017 11:01
410351,1895,KA53C1956,2017000142,2017000866,189500002,0,N,-1,-1,4/20/2017 11:01
410352,1895,KA53D0648,2018000043,2018000158,25700027,0,N,-1,-1,3/16/2018 19:34
410353,1895,KA53EC6290,2015000155,2016000339,189500013,0,N,-1,-1,5/3/2016 18:46
410354,1895,KA53EE5509,2016000202,2017000160,140100037,0,N,-1,-1,4/6/2017 13:41
410355,1895,KA53EJ7426,2016000220,2017000172,140100037,0,N,-1,-1,4/6/2017 16:51
410356,1895,KA53EP6809,2017000035,2017000229,189500022,0,N,-1,-1,4/11/2017 20:12
410357,1895,KA53EP6809,2017000035,2017000229,189500022,0,N,-1,-1,4/11/2017 20:12
410358,1895,KA53EP9367,2018000018,2018000169,139400077,0,N,-1,-1,3/20/2018 20:03
410359,1895,KA53EP9367,2018000018,2018000169,139400077,0,N,-1,-1,3/20/2018 20:03
410360,1895,KA53ER4647,2017000478,2017004207,189500025,0,N,-1,-1,12/31/2017 12:00
410361,1895,KA53ER4647,2017000478,2017004207,189500025,0,N,-1,-1,12/31/2017 12:00
410362,1895,KA53EX7689,2018000193,2019000006,189500022,0,N,-1,-1,1/5/2019 18:22
410363,1895,KA53EX7689,2018000193,2019000006,189500022,0,N,-1,-1,1/5/2019 18:22
410364,1895,KA53EX7689,2018000193,2019000006,189500022,0,N,-1,-1,1/5/2019 18:22

In [6]:
df.describe()

,Unit_ID,Crime_No,Vehicle_Owner_ID,UserID,Modified_Unit_ID,Sync_Id,Sync_Id_Old
count,410365.000000,4.103650e+05,4.103650e+05,4.103650e+05,410365.0,410365.0,410365.0
mean,1154.481011,2.016101e+09,2.016741e+09,1.004184e+08,0.0,-1.0,-1.0
std,600.568854,1.463993e+06,1.339128e+06,7.872668e+07,0.0,0.0,0.0
min,57.000000,2.014000e+09,2.014000e+09,4.500000e+01,0.0,-1.0,-1.0
25%,608.000000,2.015000e+09,2.016000e+09,4.470011e+07,0.0,-1.0,-1.0
50%,1167.000000,2.016000e+09,2.017001e+09,1.019000e+08,0.0,-1.0,-1.0
75%,1679.000000,2.017000e+09,2.018000e+09,1.470000e+08,0.0,-1.0,-1.0
max,2245.000000,2.019000e+09,2.019007e+09,1.869000e+09,0.0,-1.0,-1.0

In [8]:
df.isna().sum()

Unit_ID                 0
Registration_Number    17
Crime_No                0
Vehicle_Owner_ID        0
UserID                  0
Modified_Unit_ID        0
Action_Flag             0
Sync_Id                 0
Sync_Id_Old             0
DEDT                    0
dtype: int64

In [9]:
df.dropna(inplace=True)

In [11]:
df.columns

Index([u'Unit_ID', u'Registration_Number', u'Crime_No', u'Vehicle_Owner_ID',
       u'UserID', u'Modified_Unit_ID', u'Action_Flag', u'Sync_Id',
       u'Sync_Id_Old', u'DEDT'],
      dtype='object')

In [16]:
df.empty

False

In [19]:
df.drop(['Modified_Unit_ID','Sync_Id','Sync_Id_Old'], axis=1, inplace=True)

In [24]:
df.drop(['Action_Flag'], axis=1, inplace=True)

In [25]:
df

,Unit_ID,Registration_Number,Crime_No,Vehicle_Owner_ID,UserID,DEDT
0,57,AP26AY1382,2018000071,2018000397,4400061,7/25/2018 18:50
1,57,AP26AY1382,2018000071,2018000397,4400061,7/25/2018 18:50
2,57,AP28CK8490,2017000064,2017002647,4400014,9/25/2017 18:17
3,57,HR38Q9825,2014000243,2014001174,4000039,12/1/2014 12:28
4,57,KA-09-EU-5865,2014000111,2014000332,4100020,4/22/2014 21:01
5,57,KA-09-EU-5865,2014000111,2014000332,4100020,4/22/2014 21:01
6,57,KA-09-EU-5865,2014000111,2014000332,4100020,4/22/2014 21:01
7,57,KA-09-F-4363,2014000111,2014000330,4100020,4/22/2014 18:21
8,57,KA-09-F-4363,2014000111,2014000330,4100020,4/22/2014 18:21
9,57,KA-09-F-4363,2014000111,2014000330,4100020,4/22/2014 18:21
10,57,KA-09EY4016,2014000043,2014000140,3200150,2/22/2014 13:48
11,57,KA-10-150,2014000043,2014000138,3200150,2/22/2014 13:26
12,57,KA01C8153,2016000073,2016000372,5600028,9/7/2016 13:06
13,57,KA01C8153,2016000073,2016000372,5600028,9/7/2016 13:06
14,57,KA01C8153,2016000073,2016000372,5600028,9/7/2016 13:06
15,57,KA01EB0650,2014000176,2014000509,5300024,7/2/2014 19:44
16,57,KA01HA4212,2019000012,2019000099,4200023,2/26/2019 13:41
17,57,KA01HA4212,2019000012,2019000099,4200023,2/26/2019 13:41
18,57,KA01P5716,2018000004,2018000024,4400112,1/15/2018 11:26
19,57,KA01P5716,2018000004,2018000024,4400112,1/15/2018 11:26
20,57,KA01P9020,2018000054,2018000250,5700038,6/17/2018 18:07
21,57,KA02EF7354,2018000072,2018000417,89700010,8/12/2018 18:22
22,57,KA02EF7354,2018000072,2018000417,89700010,8/12/2018 18:22
23,57,KA02EF7354,2018000072,2018000417,89700010,8/12/2018 18:22
24,57,KA03HF652,2014000176,2014000511,5300024,7/2/2014 19:52
25,57,KA04MA4283,2014000244,2014001178,5300053,12/2/2014 11:46
26,57,KA04MA4283,2014000244,2014001178,5300053,12/2/2014 11:46
27,57,KA04MH5753,2016000059,2016000335,5600028,8/7/2016 21:08
28,57,KA05EN5476,2014000061,2014000296,5900092,4/20/2014 18:40
29,57,KA05M5108,2016000009,2016000112,5600028,3/7/2016 21:31
...,...,...,...,...,...,...
410335,1895,KA51C8444,2016000027,2016000128,189500002,4/9/2016 18:34
410336,1895,KA51C8444,2016000027,2016000128,189500002,4/9/2016 18:34
410337,1895,KA51C8444,2016000027,2016000128,189500002,4/9/2016 18:34
410338,1895,KA51D8932,2018000175,2018000861,176600065,11/26/2018 19:39
410339,1895,KA51EC1967,2015000062,2015000361,189500002,6/27/2015 11:13
410340,1895,KA51EF6863,2018000043,2018000303,189500022,4/20/2018 19:26
410341,1895,KA51MC5233,2014000004,2014000153,25900026,4/4/2014 19:37
410342,1895,KA51MC5233,2014000004,2014000153,25900026,4/4/2014 19:37
410343,1895,ka51y7115,2016000177,2017003089,189500022,5/18/2017 17:41
410344,1895,KA53-U7927,2014000054,2014000472,25900026,9/4/2014 15:45
410345,1895,KA537622,2015000105,2015000591,189500002,11/26/2015 20:44
410346,1895,KA53A3437,2016000427,2017000066,189500022,4/4/2017 20:01
410347,1895,KA53A9490,2017000053,2017000885,83100002,4/20/2017 12:47
410348,1895,KA53B0218,2015000194,2016000292,189500002,4/22/2016 19:36
410349,1895,KA53C1731,2017000410,2017004015,189500025,12/9/2017 2:25
410350,1895,KA53C1956,2017000142,2017000866,189500002,4/20/2017 11:01
410351,1895,KA53C1956,2017000142,2017000866,189500002,4/20/2017 11:01
410352,1895,KA53D0648,2018000043,2018000158,25700027,3/16/2018 19:34
410353,1895,KA53EC6290,2015000155,2016000339,189500013,5/3/2016 18:46
410354,1895,KA53EE5509,2016000202,2017000160,140100037,4/6/2017 13:41
410355,1895,KA53EJ7426,2016000220,2017000172,140100037,4/6/2017 16:51
410356,1895,KA53EP6809,2017000035,2017000229,189500022,4/11/2017 20:12
410357,1895,KA53EP6809,2017000035,2017000229,189500022,4/11/2017 20:12
410358,1895,KA53EP9367,2018000018,2018000169,139400077,3/20/2018 20:03
410359,1895,KA53EP9367,2018000018,2018000169,139400077,3/20/2018 20:03
410360,1895,KA53ER4647,2017000478,2017004207,189500025,12/31/2017 12:00
410361,1895,KA53ER4647,2017000478,2017004207,189500025,12/31/2017 12:00
410362,1895,KA53EX7689,2018000193,2019000006,189500022,1/5/2019 18:22
410363,1895,KA53EX7689,2018000193,2019000006,189500022,1/5/2019 18:22
410364,1895,KA53EX7689,2018000193,2019000006,189500022,1/5/2019 18:22

In [27]:
grouped = df.groupby(df['Registration_Number'])

In [28]:
grouped.first()

,Unit_ID,Crime_No,Vehicle_Owner_ID,UserID,DEDT
Registration_Number,,,,,
++++,816,2014000025,2014000061,189500042,3/21/2014 19:22
+++++,816,2014000031,2014000063,189500042,3/21/2014 19:27
-EO-1861,1642,2015000264,2017000109,68700045,4/28/2017 16:56
00,1059,2017000120,2017000031,121500021,4/27/2017 16:52
00000000,2133,2017000049,2017000397,28900641,9/15/2017 11:16
AA0780,884,2017000003,2017000014,133700003,1/24/2017 12:07
AA436635,1925,2014000053,2017000156,10100074,3/30/2017 10:11
AAA9105,1913,2016000191,2017003436,180800065,5/24/2017 14:03
AAN0530,228,2018000293,2019000180,107600320,1/21/2019 16:02
AAQ5337,967,2016000012,2017000084,100400035,4/25/2017 20:27
AAT1503,405,2015000122,2017001376,40400035,5/13/2017 21:26
AB09BU5074,377,2014000095,2015000937,36900090,4/4/2015 13:48
AB1234,1898,2017000176,2018000522,189800046,4/25/2018 16:30
AB13AZ7145,420,2018000031,2018000039,100500079,10/13/2018 11:50
AB1835,1464,2015000019,2015000042,42000030,3/12/2015 19:25
ABC-1583,228,2015000014,2015000223,165200073,4/6/2015 13:41
ABL0802,1258,2015000142,2015001769,44700151,12/9/2015 18:20
ABT1181,405,2016000092,2017000546,167700034,2/24/2017 11:42
ADA649,1569,2014000266,2017001361,81100059,5/9/2017 15:15
ADC8529,228,2014000182,2014001310,165200073,12/26/2014 18:43
ADD4885,276,2018000119,2019000073,28900469,2/19/2019 11:17
ADT7301,405,2014000004,2017001946,40400035,5/15/2017 9:55
ADT8526,1169,2016000001,2016000031,162800021,4/23/2016 19:16
AEA-3264,392,2015000347,2017000378,40500052,4/17/2017 13:02
AEB3702,1792,2015000042,2016000134,200730,4/19/2016 12:24
AEU9420,1477,2018000165,2019000084,146900005,7/17/2019 20:00
AEY1294,395,2016000076,2017000323,37300026,7/9/2017 13:57
AG793211,893,2016000173,2017000023,113000015,1/7/2017 12:17
AH6303,1458,2015000185,2017000317,39900043,5/20/2017 23:16
AHB2875,1922,2018000011,2018000109,40500025,3/14/2018 0:41
...,...,...,...,...,...
tn04ae7932,1775,2014000057,2014000375,176600098,10/16/2014 11:44
tn24d0186,1775,2014000062,2015000020,140100101,1/31/2015 15:24
tn281719,1091,2016000167,2017000343,4600056,4/28/2017 1:11
tn28af7810,1081,2015000097,2015000576,45400112,7/4/2015 17:43
tn28aj5398,1059,2014000066,2017001580,121500021,5/21/2017 17:46
tn28ba8451,511,2017000041,2017001497,51100018,7/24/2017 11:40
tn29ay0693,1763,2016000058,2017004900,177000109,7/28/2017 20:07
tn29n2617,1787,2016000837,2017000382,139400019,4/17/2017 16:03
tn30ay4936,1130,2015000009,2017000120,68200080,5/2/2017 14:51
tn31ah5252,1911,2016000046,2017000286,44700136,3/1/2017 13:32
tn33bf6415,1130,2015000006,2017000055,68200080,4/28/2017 11:28
tn34e9599,311,2015000005,2017002723,32300033,5/10/2017 15:50
tn34k8704,311,2015000005,2017002721,32300033,5/10/2017 15:46
tn37w8826,1130,2015000085,2017000124,68200080,5/2/2017 15:16
tn46k0687,1913,2016000103,2017002869,27700033,5/23/2017 12:56
tn52u8012,1130,2015000019,2017000185,68200080,5/3/2017 8:44
tn52z3510,894,2014000329,2017001042,136000051,5/25/2017 11:03
tn67bd0646,1521,2018000079,2018000543,49300042,9/20/2018 13:15
tn70s4866,1812,2016000086,2017000142,28900458,5/13/2017 13:57
tn72bc3233,1913,2016000366,2017001405,180800065,5/19/2017 16:03
ts03z0387,1780,2018000031,2018000340,68200375,3/8/2018 11:23
ts06ev3249,2159,2018000082,2019000044,158900405,1/20/2019 10:11
ts06ub1599,2125,2018000047,2018000240,98500020,9/27/2018 13:49
ts07uc9593,2125,2018000002,2018000073,98500018,3/30/2018 19:02
ts08ua1376,2125,2017000096,2018000002,97900028,1/3/2018 11:55
up15ba8395,1761,2017000174,2017001423,96500019,7/10/2017 19:25
up21bn4725,1782,2018000063,2018000262,200762,5/20/2018 10:42
wb41F2089,815,2014000009,2014000114,139400052,1/8/2014 11:42
xx00xx000,59,2014000026,2015000958,5700050,12/19/2015 13:25
xx00xx0000,59,2018000040,2018000231,5400067,8/16/2018 8:55

In [29]:
df

,Unit_ID,Registration_Number,Crime_No,Vehicle_Owner_ID,UserID,DEDT
0,57,AP26AY1382,2018000071,2018000397,4400061,7/25/2018 18:50
1,57,AP26AY1382,2018000071,2018000397,4400061,7/25/2018 18:50
2,57,AP28CK8490,2017000064,2017002647,4400014,9/25/2017 18:17
3,57,HR38Q9825,2014000243,2014001174,4000039,12/1/2014 12:28
4,57,KA-09-EU-5865,2014000111,2014000332,4100020,4/22/2014 21:01
5,57,KA-09-EU-5865,2014000111,2014000332,4100020,4/22/2014 21:01
6,57,KA-09-EU-5865,2014000111,2014000332,4100020,4/22/2014 21:01
7,57,KA-09-F-4363,2014000111,2014000330,4100020,4/22/2014 18:21
8,57,KA-09-F-4363,2014000111,2014000330,4100020,4/22/2014 18:21
9,57,KA-09-F-4363,2014000111,2014000330,4100020,4/22/2014 18:21
10,57,KA-09EY4016,2014000043,2014000140,3200150,2/22/2014 13:48
11,57,KA-10-150,2014000043,2014000138,3200150,2/22/2014 13:26
12,57,KA01C8153,2016000073,2016000372,5600028,9/7/2016 13:06
13,57,KA01C8153,2016000073,2016000372,5600028,9/7/2016 13:06
14,57,KA01C8153,2016000073,2016000372,5600028,9/7/2016 13:06
15,57,KA01EB0650,2014000176,2014000509,5300024,7/2/2014 19:44
16,57,KA01HA4212,2019000012,2019000099,4200023,2/26/2019 13:41
17,57,KA01HA4212,2019000012,2019000099,4200023,2/26/2019 13:41
18,57,KA01P5716,2018000004,2018000024,4400112,1/15/2018 11:26
19,57,KA01P5716,2018000004,2018000024,4400112,1/15/2018 11:26
20,57,KA01P9020,2018000054,2018000250,5700038,6/17/2018 18:07
21,57,KA02EF7354,2018000072,2018000417,89700010,8/12/2018 18:22
22,57,KA02EF7354,2018000072,2018000417,89700010,8/12/2018 18:22
23,57,KA02EF7354,2018000072,2018000417,89700010,8/12/2018 18:22
24,57,KA03HF652,2014000176,2014000511,5300024,7/2/2014 19:52
25,57,KA04MA4283,2014000244,2014001178,5300053,12/2/2014 11:46
26,57,KA04MA4283,2014000244,2014001178,5300053,12/2/2014 11:46
27,57,KA04MH5753,2016000059,2016000335,5600028,8/7/2016 21:08
28,57,KA05EN5476,2014000061,2014000296,5900092,4/20/2014 18:40
29,57,KA05M5108,2016000009,2016000112,5600028,3/7/2016 21:31
...,...,...,...,...,...,...
410335,1895,KA51C8444,2016000027,2016000128,189500002,4/9/2016 18:34
410336,1895,KA51C8444,2016000027,2016000128,189500002,4/9/2016 18:34
410337,1895,KA51C8444,2016000027,2016000128,189500002,4/9/2016 18:34
410338,1895,KA51D8932,2018000175,2018000861,176600065,11/26/2018 19:39
410339,1895,KA51EC1967,2015000062,2015000361,189500002,6/27/2015 11:13
410340,1895,KA51EF6863,2018000043,2018000303,189500022,4/20/2018 19:26
410341,1895,KA51MC5233,2014000004,2014000153,25900026,4/4/2014 19:37
410342,1895,KA51MC5233,2014000004,2014000153,25900026,4/4/2014 19:37
410343,1895,ka51y7115,2016000177,2017003089,189500022,5/18/2017 17:41
410344,1895,KA53-U7927,2014000054,2014000472,25900026,9/4/2014 15:45
410345,1895,KA537622,2015000105,2015000591,189500002,11/26/2015 20:44
410346,1895,KA53A3437,2016000427,2017000066,189500022,4/4/2017 20:01
410347,1895,KA53A9490,2017000053,2017000885,83100002,4/20/2017 12:47
410348,1895,KA53B0218,2015000194,2016000292,189500002,4/22/2016 19:36
410349,1895,KA53C1731,2017000410,2017004015,189500025,12/9/2017 2:25
410350,1895,KA53C1956,2017000142,2017000866,189500002,4/20/2017 11:01
410351,1895,KA53C1956,2017000142,2017000866,189500002,4/20/2017 11:01
410352,1895,KA53D0648,2018000043,2018000158,25700027,3/16/2018 19:34
410353,1895,KA53EC6290,2015000155,2016000339,189500013,5/3/2016 18:46
410354,1895,KA53EE5509,2016000202,2017000160,140100037,4/6/2017 13:41
410355,1895,KA53EJ7426,2016000220,2017000172,140100037,4/6/2017 16:51
410356,1895,KA53EP6809,2017000035,2017000229,189500022,4/11/2017 20:12
410357,1895,KA53EP6809,2017000035,2017000229,189500022,4/11/2017 20:12
410358,1895,KA53EP9367,2018000018,2018000169,139400077,3/20/2018 20:03
410359,1895,KA53EP9367,2018000018,2018000169,139400077,3/20/2018 20:03
410360,1895,KA53ER4647,2017000478,2017004207,189500025,12/31/2017 12:00
410361,1895,KA53ER4647,2017000478,2017004207,189500025,12/31/2017 12:00
410362,1895,KA53EX7689,2018000193,2019000006,189500022,1/5/2019 18:22
410363,1895,KA53EX7689,2018000193,2019000006,189500022,1/5/2019 18:22
410364,1895,KA53EX7689,2018000193,2019000006,189500022,1/5/2019 18:22

In [31]:
df.describe()

             Unit_ID      Crime_No  Vehicle_Owner_ID        UserID
count  410348.000000  4.103480e+05      4.103480e+05  4.103480e+05
mean     1154.493854  2.016101e+09      2.016741e+09  1.004184e+08
std       600.572610  1.463972e+06      1.339121e+06  7.872718e+07
min        57.000000  2.014000e+09      2.014000e+09  4.500000e+01
25%       608.000000  2.015000e+09      2.016000e+09  4.470011e+07
50%      1167.000000  2.016000e+09      2.017001e+09  1.019000e+08
75%      1679.000000  2.017000e+09      2.018000e+09  1.470000e+08
max      2245.000000  2.019000e+09      2.019007e+09  1.869000e+09

In [33]:
df.drop_duplicates(subset=['Registration_Number'])

,Unit_ID,Registration_Number,Crime_No,Vehicle_Owner_ID,UserID,DEDT
0,57,AP26AY1382,2018000071,2018000397,4400061,7/25/2018 18:50
2,57,AP28CK8490,2017000064,2017002647,4400014,9/25/2017 18:17
3,57,HR38Q9825,2014000243,2014001174,4000039,12/1/2014 12:28
4,57,KA-09-EU-5865,2014000111,2014000332,4100020,4/22/2014 21:01
7,57,KA-09-F-4363,2014000111,2014000330,4100020,4/22/2014 18:21
10,57,KA-09EY4016,2014000043,2014000140,3200150,2/22/2014 13:48
11,57,KA-10-150,2014000043,2014000138,3200150,2/22/2014 13:26
12,57,KA01C8153,2016000073,2016000372,5600028,9/7/2016 13:06
15,57,KA01EB0650,2014000176,2014000509,5300024,7/2/2014 19:44
16,57,KA01HA4212,2019000012,2019000099,4200023,2/26/2019 13:41
18,57,KA01P5716,2018000004,2018000024,4400112,1/15/2018 11:26
20,57,KA01P9020,2018000054,2018000250,5700038,6/17/2018 18:07
21,57,KA02EF7354,2018000072,2018000417,89700010,8/12/2018 18:22
24,57,KA03HF652,2014000176,2014000511,5300024,7/2/2014 19:52
25,57,KA04MA4283,2014000244,2014001178,5300053,12/2/2014 11:46
27,57,KA04MH5753,2016000059,2016000335,5600028,8/7/2016 21:08
28,57,KA05EN5476,2014000061,2014000296,5900092,4/20/2014 18:40
29,57,KA05M5108,2016000009,2016000112,5600028,3/7/2016 21:31
31,57,KA05MM3094,2017000063,2017002426,5300083,7/19/2017 13:08
32,57,KA05MQ1295,2015000034,2015000183,5600028,5/7/2015 20:13
34,57,KA068718,2017000063,2017002575,205600002,7/27/2017 13:21
35,57,KA098169,2015000001,2015000014,125900011,1/11/2015 12:51
36,57,KA098426,2014000061,2014000294,5900092,4/20/2014 18:36
37,57,KA09A4520,2018000089,2018000449,6000001,10/1/2018 10:50
40,57,KA09B0864,2016000056,2016000321,5800023,7/28/2016 20:02
41,57,KA09EC5648,2014000108,2014000731,5600028,7/18/2014 20:41
44,57,KA09EG9114,2014000175,2014000505,5900073,7/2/2014 13:41
45,57,KA09EM1651,2014000044,2014000579,5600028,7/11/2014 19:34
46,57,KA09ET5253,2014000044,2014000577,5600028,7/11/2014 19:27
47,57,KA09EU6725,2014000094,2014000546,5900073,7/8/2014 19:04
...,...,...,...,...,...,...
410322,2014,KA05TB5455,2014000054,2014000109,4400046,10/20/2014 13:12
410323,2014,KA09EQ2663,2015000019,2015000081,4400046,2/5/2015 11:25
410324,2014,KA09EV7551,2017000074,2017000946,28400030,5/23/2017 17:51
410325,2014,KA09EZ6908,2014000079,2017000827,28400030,5/14/2017 19:43
410327,2014,KA09HK2590,2017000142,2017001380,4000030,9/12/2017 11:05
410328,2014,KA09N6561,2015000062,2015000376,87900065,6/10/2015 10:35
410329,2014,KA11R2727,2015000062,2015000374,87900065,6/10/2015 10:06
410331,2014,KA55K3110,2015000080,2015000300,87900065,5/27/2015 19:47
410332,1895,KA41A3034,2014000204,2017003522,189500022,7/25/2017 11:45
410333,1895,KA41A4037,2014000054,2014000470,25900026,9/4/2014 15:26
410334,1895,KA51C4365,2019000001,2019000041,176600065,1/18/2019 13:32
410335,1895,KA51C8444,2016000027,2016000128,189500002,4/9/2016 18:34
410338,1895,KA51D8932,2018000175,2018000861,176600065,11/26/2018 19:39
410339,1895,KA51EC1967,2015000062,2015000361,189500002,6/27/2015 11:13
410340,1895,KA51EF6863,2018000043,2018000303,189500022,4/20/2018 19:26
410341,1895,KA51MC5233,2014000004,2014000153,25900026,4/4/2014 19:37
410343,1895,ka51y7115,2016000177,2017003089,189500022,5/18/2017 17:41
410344,1895,KA53-U7927,2014000054,2014000472,25900026,9/4/2014 15:45
410345,1895,KA537622,2015000105,2015000591,189500002,11/26/2015 20:44
410346,1895,KA53A3437,2016000427,2017000066,189500022,4/4/2017 20:01
410349,1895,KA53C1731,2017000410,2017004015,189500025,12/9/2017 2:25
410350,1895,KA53C1956,2017000142,2017000866,189500002,4/20/2017 11:01
410352,1895,KA53D0648,2018000043,2018000158,25700027,3/16/2018 19:34
410353,1895,KA53EC6290,2015000155,2016000339,189500013,5/3/2016 18:46
410354,1895,KA53EE5509,2016000202,2017000160,140100037,4/6/2017 13:41
410355,1895,KA53EJ7426,2016000220,2017000172,140100037,4/6/2017 16:51
410356,1895,KA53EP6809,2017000035,2017000229,189500022,4/11/2017 20:12
410358,1895,KA53EP9367,2018000018,2018000169,139400077,3/20/2018 20:03
410360,1895,KA53ER4647,2017000478,2017004207,189500025,12/31/2017 12:00
410362,1895,KA53EX7689,2018000193,2019000006,189500022,1/5/2019 18:22

In [58]:
def category(num):
    import ast
    
    if ast.literal_eval(num[:-3]) > 0 and ast.literal_eval(num[:-3]) <=3:
        return "0-3"
    elif ast.literal_eval(num[:-3]) > 3 and ast.literal_eval(num[:-3]) <=6:
        return "3-6"
    elif ast.literal_eval(num[:-3]) > 6 and ast.literal_eval(num[:-3]) <=9:
        return "6-9"
    elif ast.literal_eval(num[:-3]) > 9 and ast.literal_eval(num[:-3]) <=12:
        return "9-12"
    elif ast.literal_eval(num[:-3]) > 12 and ast.literal_eval(num[:-3]) <=15:
        return "12-15"
    elif ast.literal_eval(num[:-3]) > 15 and ast.literal_eval(num[:-3]) <=18:
        return "15-18"
    elif ast.literal_eval(num[:-3]) > 18 and ast.literal_eval(num[:-3]) <=21:
        return "18-21"
    elif ast.literal_eval(num[:-3]) > 21:
        return "21-24"

In [60]:
time_frame = df['DEDT'].apply(lambda x : str(x[-5:]))
df['Time'] = time_frame
df['Date'] = df['DEDT'].apply(lambda x:str(x[:-5]))

In [61]:
df

,Unit_ID,Registration_Number,Crime_No,Vehicle_Owner_ID,UserID,DEDT,Time,Date
0,57,AP26AY1382,2018000071,2018000397,4400061,7/25/2018 18:50,18:50,7/25/2018
1,57,AP26AY1382,2018000071,2018000397,4400061,7/25/2018 18:50,18:50,7/25/2018
2,57,AP28CK8490,2017000064,2017002647,4400014,9/25/2017 18:17,18:17,9/25/2017
3,57,HR38Q9825,2014000243,2014001174,4000039,12/1/2014 12:28,12:28,12/1/2014
4,57,KA-09-EU-5865,2014000111,2014000332,4100020,4/22/2014 21:01,21:01,4/22/2014
5,57,KA-09-EU-5865,2014000111,2014000332,4100020,4/22/2014 21:01,21:01,4/22/2014
6,57,KA-09-EU-5865,2014000111,2014000332,4100020,4/22/2014 21:01,21:01,4/22/2014
7,57,KA-09-F-4363,2014000111,2014000330,4100020,4/22/2014 18:21,18:21,4/22/2014
8,57,KA-09-F-4363,2014000111,2014000330,4100020,4/22/2014 18:21,18:21,4/22/2014
9,57,KA-09-F-4363,2014000111,2014000330,4100020,4/22/2014 18:21,18:21,4/22/2014
10,57,KA-09EY4016,2014000043,2014000140,3200150,2/22/2014 13:48,13:48,2/22/2014
11,57,KA-10-150,2014000043,2014000138,3200150,2/22/2014 13:26,13:26,2/22/2014
12,57,KA01C8153,2016000073,2016000372,5600028,9/7/2016 13:06,13:06,9/7/2016
13,57,KA01C8153,2016000073,2016000372,5600028,9/7/2016 13:06,13:06,9/7/2016
14,57,KA01C8153,2016000073,2016000372,5600028,9/7/2016 13:06,13:06,9/7/2016
15,57,KA01EB0650,2014000176,2014000509,5300024,7/2/2014 19:44,19:44,7/2/2014
16,57,KA01HA4212,2019000012,2019000099,4200023,2/26/2019 13:41,13:41,2/26/2019
17,57,KA01HA4212,2019000012,2019000099,4200023,2/26/2019 13:41,13:41,2/26/2019
18,57,KA01P5716,2018000004,2018000024,4400112,1/15/2018 11:26,11:26,1/15/2018
19,57,KA01P5716,2018000004,2018000024,4400112,1/15/2018 11:26,11:26,1/15/2018
20,57,KA01P9020,2018000054,2018000250,5700038,6/17/2018 18:07,18:07,6/17/2018
21,57,KA02EF7354,2018000072,2018000417,89700010,8/12/2018 18:22,18:22,8/12/2018
22,57,KA02EF7354,2018000072,2018000417,89700010,8/12/2018 18:22,18:22,8/12/2018
23,57,KA02EF7354,2018000072,2018000417,89700010,8/12/2018 18:22,18:22,8/12/2018
24,57,KA03HF652,2014000176,2014000511,5300024,7/2/2014 19:52,19:52,7/2/2014
25,57,KA04MA4283,2014000244,2014001178,5300053,12/2/2014 11:46,11:46,12/2/2014
26,57,KA04MA4283,2014000244,2014001178,5300053,12/2/2014 11:46,11:46,12/2/2014
27,57,KA04MH5753,2016000059,2016000335,5600028,8/7/2016 21:08,21:08,8/7/2016
28,57,KA05EN5476,2014000061,2014000296,5900092,4/20/2014 18:40,18:40,4/20/2014
29,57,KA05M5108,2016000009,2016000112,5600028,3/7/2016 21:31,21:31,3/7/2016
...,...,...,...,...,...,...,...,...
410335,1895,KA51C8444,2016000027,2016000128,189500002,4/9/2016 18:34,18:34,4/9/2016
410336,1895,KA51C8444,2016000027,2016000128,189500002,4/9/2016 18:34,18:34,4/9/2016
410337,1895,KA51C8444,2016000027,2016000128,189500002,4/9/2016 18:34,18:34,4/9/2016
410338,1895,KA51D8932,2018000175,2018000861,176600065,11/26/2018 19:39,19:39,11/26/2018
410339,1895,KA51EC1967,2015000062,2015000361,189500002,6/27/2015 11:13,11:13,6/27/2015
410340,1895,KA51EF6863,2018000043,2018000303,189500022,4/20/2018 19:26,19:26,4/20/2018
410341,1895,KA51MC5233,2014000004,2014000153,25900026,4/4/2014 19:37,19:37,4/4/2014
410342,1895,KA51MC5233,2014000004,2014000153,25900026,4/4/2014 19:37,19:37,4/4/2014
410343,1895,ka51y7115,2016000177,2017003089,189500022,5/18/2017 17:41,17:41,5/18/2017
410344,1895,KA53-U7927,2014000054,2014000472,25900026,9/4/2014 15:45,15:45,9/4/2014
410345,1895,KA537622,2015000105,2015000591,189500002,11/26/2015 20:44,20:44,11/26/2015
410346,1895,KA53A3437,2016000427,2017000066,189500022,4/4/2017 20:01,20:01,4/4/2017
410347,1895,KA53A9490,2017000053,2017000885,83100002,4/20/2017 12:47,12:47,4/20/2017
410348,1895,KA53B0218,2015000194,2016000292,189500002,4/22/2016 19:36,19:36,4/22/2016
410349,1895,KA53C1731,2017000410,2017004015,189500025,12/9/2017 2:25,2:25,12/9/2017
410350,1895,KA53C1956,2017000142,2017000866,189500002,4/20/2017 11:01,11:01,4/20/2017
410351,1895,KA53C1956,2017000142,2017000866,189500002,4/20/2017 11:01,11:01,4/20/2017
410352,1895,KA53D0648,2018000043,2018000158,25700027,3/16/2018 19:34,19:34,3/16/2018
410353,1895,KA53EC6290,2015000155,2016000339,189500013,5/3/2016 18:46,18:46,5/3/2016
410354,1895,KA53EE5509,2016000202,2017000160,140100037,4/6/2017 13:41,13:41,4/6/2017
410355,1895,KA53EJ7426,2016000220,2017000172,140100037,4/6/2017 16:51,16:51,4/6/2017
410356,1895,KA53EP6809,2017000035,2017000229,189500022,4/11/2017 20:12,20:12,4/11/2017
410357,1895,KA53EP6809,2017000035,2017000229,189500022,4/11/2017 20:12,20:12,4/11/2017
410358,1895,KA53EP9367,2018000018,2018000169,139400077,3/20/2018 20:03,20:03,3/20/2018
410359,1895,KA53EP9367,2018000018,2018000169,139400077,3/20/2018 20:03,20:03,3/20/2018
410360,1895,KA53ER4647,2017000478,2017004207,189500025,12/31/2017 12:00,12:00,12/31/2017
410361,1895,KA53ER4647,2017000478,2017004207,189500025,12/31/2017 12:00,12:00,12/31/2017
410362,1895,KA53EX7689,2018000193,2019000006,189500022,1/5/2019 18:22,18:22,1/5/2019
410363,1895,KA53EX7689,2018000193,2019000006,189500022,1/5/2019 18:22,18:22,1/5/2019
410364,1895,KA53EX7689,2018000193,2019000006,189500022,1/5/2019 18:22,18:22,1/5/2019

In [63]:
df.drop_duplicates(subset=['UserID'], inplace = True)

In [64]:
df

,Unit_ID,Registration_Number,Crime_No,Vehicle_Owner_ID,UserID,DEDT,Time,Date
0,57,AP26AY1382,2018000071,2018000397,4400061,7/25/2018 18:50,18:50,7/25/2018
2,57,AP28CK8490,2017000064,2017002647,4400014,9/25/2017 18:17,18:17,9/25/2017
3,57,HR38Q9825,2014000243,2014001174,4000039,12/1/2014 12:28,12:28,12/1/2014
4,57,KA-09-EU-5865,2014000111,2014000332,4100020,4/22/2014 21:01,21:01,4/22/2014
10,57,KA-09EY4016,2014000043,2014000140,3200150,2/22/2014 13:48,13:48,2/22/2014
12,57,KA01C8153,2016000073,2016000372,5600028,9/7/2016 13:06,13:06,9/7/2016
15,57,KA01EB0650,2014000176,2014000509,5300024,7/2/2014 19:44,19:44,7/2/2014
16,57,KA01HA4212,2019000012,2019000099,4200023,2/26/2019 13:41,13:41,2/26/2019
18,57,KA01P5716,2018000004,2018000024,4400112,1/15/2018 11:26,11:26,1/15/2018
20,57,KA01P9020,2018000054,2018000250,5700038,6/17/2018 18:07,18:07,6/17/2018
21,57,KA02EF7354,2018000072,2018000417,89700010,8/12/2018 18:22,18:22,8/12/2018
25,57,KA04MA4283,2014000244,2014001178,5300053,12/2/2014 11:46,11:46,12/2/2014
28,57,KA05EN5476,2014000061,2014000296,5900092,4/20/2014 18:40,18:40,4/20/2014
31,57,KA05MM3094,2017000063,2017002426,5300083,7/19/2017 13:08,13:08,7/19/2017
34,57,KA068718,2017000063,2017002575,205600002,7/27/2017 13:21,13:21,7/27/2017
35,57,KA098169,2015000001,2015000014,125900011,1/11/2015 12:51,12:51,1/11/2015
37,57,KA09A4520,2018000089,2018000449,6000001,10/1/2018 10:50,10:50,10/1/2018
40,57,KA09B0864,2016000056,2016000321,5800023,7/28/2016 20:02,20:02,7/28/2016
44,57,KA09EG9114,2014000175,2014000505,5900073,7/2/2014 13:41,13:41,7/2/2014
55,57,KA09HC5175,2018000122,2019000016,5700014,1/24/2019 17:31,17:31,1/24/2019
68,57,KA03ED5243,2014000189,2014000903,5300032,8/4/2014 20:08,20:08,8/4/2014
86,57,KA09EG9547,2015000002,2015000018,4600016,1/20/2015 18:55,18:55,1/20/2015
129,57,KA-09-ER-1521,2014000097,2014000286,5900083,4/12/2014 19:29,19:29,4/12/2014
133,57,KA01EK5964,2016000027,2016000177,5700007,4/21/2016 11:28,11:28,4/21/2016
137,57,KA05AC6218,2018000061,2018000359,3200138,7/19/2018 20:55,20:55,7/19/2018
191,57,KA-13-1009,2014000161,2014000440,4400046,6/13/2014 18:57,18:57,6/13/2014
193,57,KA01AA1744,2018000053,2018000232,5600020,6/9/2018 20:52,20:52,6/9/2018
201,57,KA05MQ0951,2017000082,2017002664,4400115,10/11/2017 12:56,12:56,10/11/2017
203,57,KA09B0404,2018000104,2018000540,4600078,11/11/2018 13:35,13:35,11/11/2018
223,57,KA09HH1807,2018000040,2018000224,5600027,6/2/2018 20:36,20:36,6/2/2018
...,...,...,...,...,...,...,...,...
405128,2159,KA33q9644,2018000034,2018000258,158900251,9/15/2018 10:14,10:14,9/15/2018
405412,2160,KA11EG5652,2017000326,2018000034,84800005,1/27/2018 10:27,10:27,1/27/2018
405427,2161,KA02H7729,2018000203,2019000002,87100018,2/22/2019 12:00,12:00,2/22/2019
405429,2161,KA13T6745,2017000031,2017000008,85700033,4/1/2017 18:14,18:14,4/1/2017
405505,2161,KA03AF4221,2018000188,2018000048,84400027,10/20/2018 11:16,11:16,10/20/2018
405553,2161,KA09B3761,2017000052,2017000014,161800021,5/2/2017 18:49,18:49,5/2/2017
405554,2161,KA11S6781,2018000110,2018000026,86400007,5/18/2018 18:21,18:21,5/18/2018
405786,1934,KA129719,2014000062,2014002288,107700554,11/9/2014 17:55,17:55,11/9/2014
405828,1932,AP22Y3925,2018000007,2018000046,99200014,7/8/2018 19:11,19:11,7/8/2018
406014,1932,KA36EN7899,2017000025,2018000032,95800213,3/14/2018 13:23,13:23,3/14/2018
406033,2159,KA33R4964,2018000030,2018000252,158900464,9/7/2018 11:29,11:29,9/7/2018
406188,2161,KA04EW1437,2019000003,2019000050,85700038,10/1/2019 13:43,13:43,10/1/2019
406515,2138,KA20D0476,2017000172,2018000002,58300005,1/7/2018 12:29,12:29,1/7/2018
406547,2155,KA-55-U-8903,2017000081,2017000516,89700036,8/17/2017 12:41,12:41,8/17/2017
406893,2161,KA11EK8377,2018000197,2018000052,85800001,11/30/2018 19:58,19:58,11/30/2018
407427,2014,KA-55-E-5253,2018000210,2018001039,201400001,12/3/2018 12:49,12:49,12/3/2018
407722,2014,KA-09-HA-6982,2017000109,2017001292,4200058,8/9/2017 13:23,13:23,8/9/2017
408086,1895,KA28EE9229,2015000029,2015000194,68200516,4/25/2015 20:27,20:27,4/25/2015
408293,1932,KA36EL6635,2018000012,2018000069,1400025,12/28/2018 17:49,17:49,12/28/2018
408413,1895,KA53EA7561,2017000236,2017003097,25800009,6/18/2017 13:59,13:59,6/18/2017
408609,1895,KA40X7848,2017000340,2017003593,25700004,8/6/2017 17:38,17:38,8/6/2017
408623,1895,KA53B4426,2015000043,2015000356,189500014,6/26/2015 18:21,18:21,6/26/2015
408920,2132,KA02MD0693,2019000007,2019000410,179211128,9/6/2019 17:14,17:14,9/6/2019
408964,1895,KA03HM8210,2015000074,2015000574,200249,11/21/2015 18:16,18:16,11/21/2015
409004,2133,KA23R4925,2018000047,2018000297,14820037,6/14/2018 13:09,13:09,6/14/2018
409032,2138,KA12B1185,2017000114,2017000244,58300017,10/28/2017 12:42,12:42,10/28/2017
409034,2138,KA12L8233,2017000114,2017000252,58800019,11/9/2017 10:43,10:43,11/9/2017
409842,2213,KA27A8921,2017000012,2017000046,13700047,6/4/2017 14:00,14:00,6/4/2017
409859,2216,MH-14BA-6031,2018000002,2018000006,42000064,1/18/2018 18:04,18:04,1/18/2018
410352,1895,KA53D0648,2018000043,2018000158,25700027,3/16/2018 19:34,19:34,3/16/2018

In [65]:
df.to_csv('Vehicle_Accidents_Time_Based.csv')

In [66]:
def process_data(filename):
    
    import time
    import ast
    import pandas as pd
    import numpy as np
    
    df = pd.read_csv(filename)
    print (df.columns)
    try:
        print(df.isna().sum())
        df.dropna(inplace=True)
        df.drop(['Modified_Unit_ID','Sync_Id','Sync_Id_Old'], axis=1, inplace=True)
        df.drop(['Action_Flag'], axis=1, inplace=True)
        df.drop_duplicates(subset=['Registration_Number'])
        time_frame = df['DEDT'].apply(lambda x : str(x[-5:]))
        df['Time'] = time_frame
        df['Date'] = df['DEDT'].apply(lambda x:str(x[:-5]))
        df.drop_duplicates(subset=['UserID'], inplace = True)
    except Exception as e:
        print(e)
        pass
    
    print('Save returned df as a file')
    return df